import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/**
 * La classe PositionXYPlotFrame é un frame che permette di visualizzare 
 * 
 * @author Andrea Rauso
 */
public class PositionXYPlotFrame extends javax.swing.JFrame {

    /**
     * Posizione sull'asse X
     */
    private float positionX; 
    
    /**
     * Posizione sull'asse Y
     */
    private float positionY;

    /**
     * Creates new form PositionXYPlotFrame
     */
    public PositionXYPlotFrame(int PositionX, int PositionY) {
        initComponents();
        setSize(600, 400);
        setTitle("DCS Posizione drone vista di profilo");
        this.positionX = PositionX;
        this.positionY = PositionY;
        // Create Dataset
        XYDataset dataset = createDataset();

        //Create chart
        JFreeChart chart = ChartFactory.createScatterPlot(
                "Simulatore dati posizione DJI Tello, vista di profilo", //Chart Title
                "Posizione Asse X", // Category axis
                "Posizione Asse Y", // Value axis
                dataset
        );

        XYPlot xyPlot = (XYPlot) chart.getPlot();
        xyPlot.setDomainCrosshairVisible(true);
        xyPlot.setRangeCrosshairVisible(true);
        XYItemRenderer renderer = xyPlot.getRenderer();
        renderer.setSeriesPaint(0, Color.blue);
        NumberAxis domain = (NumberAxis) xyPlot.getDomainAxis();
        domain.setRange(getPositionX()-10,getPositionX()+10);
        domain.setTickUnit(new NumberTickUnit(1));
        domain.setVerticalTickLabels(true);
        NumberAxis range = (NumberAxis) xyPlot.getRangeAxis();
        range.setRange(getPositionY()-5,getPositionY()+5);
        range.setTickUnit(new NumberTickUnit(1));
        
        ChartPanel panel = new ChartPanel(chart);       
        XYPositionChart.setLayout(new java.awt.BorderLayout());
        XYPositionChart.add(panel,BorderLayout.CENTER);
        XYPositionChart.validate();
        
    }
    private XYDataset createDataset() {
        XYSeriesCollection dataset = new XYSeriesCollection();

        XYSeries position = new XYSeries("Posizione");
                
        position.add(this.positionX,this.positionY);
        dataset.addSeries(position);
        
        return dataset;
    }
    
    private void updateAxesChart(){
        XYDataset dataset = createDataset();
        JFreeChart chart = ChartFactory.createScatterPlot(
                "Simulatore dati posizione DJI Tello, vista di profilo", //Chart Title
                "Poszione asse X", // Category axis
                "Poszione asse Y", // Value axis
                dataset
        );
        
        XYPlot xyPlot = (XYPlot) chart.getPlot();
        xyPlot.setDomainCrosshairVisible(true);
        xyPlot.setRangeCrosshairVisible(true);
        XYItemRenderer renderer = xyPlot.getRenderer();
        renderer.setSeriesPaint(0, Color.red);
        NumberAxis domain = (NumberAxis) xyPlot.getDomainAxis();
        domain.setRange(getPositionX()-10,getPositionX()+10);
        domain.setTickUnit(new NumberTickUnit(1));
        domain.setVerticalTickLabels(true);
        NumberAxis range = (NumberAxis) xyPlot.getRangeAxis();
        range.setRange(getPositionY()-5,getPositionY()+5);
        range.setTickUnit(new NumberTickUnit(1));
        
        ChartPanel panel = new ChartPanel(chart);
        XYPositionChart.revalidate();
        XYPositionChart.add(panel);
        XYPositionChart.validate();
    }
    
    public float getPositionX() {
        return positionX;
    }

    public float getPositionY() {
        return positionY;
    }
    

    public void setPositionX(float positionX) {
        this.positionX += positionX;
        updateAxesChart();
    }

    public void setPositionY(float positionY) {
        this.positionY += positionY;
        updateAxesChart();
    }           

    /**
     * Creates new form PositionXYPlotFrame
     */
    public PositionXYPlotFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XYPositionChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout XYPositionChartLayout = new javax.swing.GroupLayout(XYPositionChart);
        XYPositionChart.setLayout(XYPositionChartLayout);
        XYPositionChartLayout.setHorizontalGroup(
            XYPositionChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        XYPositionChartLayout.setVerticalGroup(
            XYPositionChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(XYPositionChart, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PositionXYPlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PositionXYPlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PositionXYPlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PositionXYPlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PositionXYPlotFrame(-3,3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel XYPositionChart;
    // End of variables declaration//GEN-END:variables
}
