
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * La classe RotationChartFrame é un frame che permette di visualizzare i dati
 * relativi alla rotazione del drone sui tre assi cartesiani
 * 
 * @author Andrea Rauso
 */
public class RotationChartFrame extends javax.swing.JFrame {

    /**
     * Rotazione sull'asse X (Pitch)
     */
    private int pitch; 
    
    /**
     * Rotazione sull'asse Y (Yaw)
     */
    private int yaw; 
    
    /**
     * Rotazione sull'asse Z (Roll)
     */
    private int roll; 
    
    
    /**
     * Creates new form AxesChartFrame
     * 
     * @param pitch rotazione sull'asse X
     * @param yaw rotazione sull'asse Y
     * @param roll rotazione sull'asse Z
     */
    public RotationChartFrame(int pitch, int yaw, int roll) {
        initComponents();
        setSize(600, 400);
        setTitle("DCS Grafico assi di rotazione");
        this.pitch = pitch;
        this.yaw = yaw;
        this.roll = roll;

        CategoryDataset dataset = createDataset();


        JFreeChart chart = ChartFactory.createBarChart(
                "Simulatore dati DJI Tello rotazione del drone", //Chart Title
                "Assi di rotazione", // Category axis
                "Valore rotazione", 
                dataset
        );

        ChartPanel panel = new ChartPanel(chart);
        rotationChart.setLayout(new java.awt.BorderLayout());
        rotationChart.add(panel,BorderLayout.CENTER);
        rotationChart.validate();
        
    }
    private CategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.addValue(this.pitch, "Asse", "Pitch (Beccheggio)");
        dataset.addValue(this.yaw, "Asse", "Yaw(Imbardata)");
        dataset.addValue(this.roll, "Asse", "Roll (Rollio)");
        return dataset;
    }
    
    private void updateAxesChart(){
        CategoryDataset dataset = createDataset();
        
        JFreeChart chart = ChartFactory.createBarChart(
                "Simulatore dati rotazione DJI Tello", 
                "Dati Sensori", 
                "Valore sensore", 
                dataset
        );
        
        ChartPanel panel = new ChartPanel(chart);
        rotationChart.revalidate();
        rotationChart.add(panel);
        rotationChart.validate();
    }
    
    //pitch
    public int getPitch() {
        return pitch;
    }
    
    //yaw
    public int getYaw() {
        return yaw;
    }

    //roll
    public int getRoll() {
        return roll;
    }
    
    public void setYaw(int yaw) {
        this.yaw += yaw;
        updateAxesChart();
    }

    public void setPitch(int pitch) {
        this.pitch += pitch;
        updateAxesChart();
    }

    public void setRoll(int roll) {
        this.roll += roll;
        updateAxesChart();
    }           

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotationChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout rotationChartLayout = new javax.swing.GroupLayout(rotationChart);
        rotationChart.setLayout(rotationChartLayout);
        rotationChartLayout.setHorizontalGroup(
            rotationChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        rotationChartLayout.setVerticalGroup(
            rotationChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(rotationChart, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RotationChartFrame(0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rotationChart;
    // End of variables declaration//GEN-END:variables
}
