
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea Rauso
 */
public class RotationChartFrame extends javax.swing.JFrame {

    private float rotationY; //yaw
    private float rotationX; //pitch
    private float rotationZ; //roll

    /**
     * Creates new form AxesChartFrame
     */
    public RotationChartFrame(int rotationX, int rotationY, int rotationZ) {
        initComponents();
        setSize(600, 400);
        setTitle("DCS Grafico assi di rotazione");
        this.rotationX = rotationX;
        this.rotationY = rotationY;
        this.rotationZ = rotationZ;
        // Create Dataset
        CategoryDataset dataset = createDataset();

        //Create chart
        JFreeChart chart = ChartFactory.createBarChart(
                "Simulatore dati DJI Tello", //Chart Title
                "Dati Sensori", // Category axis
                "Valore sensore", // Value axis
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false
        );

        ChartPanel panel = new ChartPanel(chart);
        rotationChart.setLayout(new java.awt.BorderLayout());
        rotationChart.add(panel,BorderLayout.CENTER);
        rotationChart.validate();
        
    }
    private CategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Population in 2005
        dataset.addValue(this.rotationY, "Sensore", "Yaw(Imbardata)");
        dataset.addValue(this.rotationX, "Sensore", "Pitch (Beccheggio)");
        dataset.addValue(this.rotationZ, "Sensore", "Roll (Rollio)");
        return dataset;
    }
    
    private void updateAxesChart(){
        CategoryDataset dataset = createDataset();
        JFreeChart chart = ChartFactory.createBarChart(
                "Simulatore dati rotazione DJI Tello", //Chart Title
                "Dati Sensori", // Category axis
                "Valore sensore", // Value axis
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false
        );
        ChartPanel panel = new ChartPanel(chart);
        rotationChart.revalidate();
        rotationChart.add(panel);
        rotationChart.validate();
    }
    
    public float getRotationY() {
        return rotationY;
    }

    public float getRotationX() {
        return rotationX;
    }

    public float getRotationZ() {
        return rotationZ;
    }
    
    public void setRotationY(float rotationY) {
        this.rotationY += rotationY;
        updateAxesChart();
    }

    public void setRotationX(float rotationX) {
        this.rotationX += rotationX;
        updateAxesChart();
    }

    public void setRotationZ(float rotationZ) {
        this.rotationZ += rotationZ;
        updateAxesChart();
    }           

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotationChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout rotationChartLayout = new javax.swing.GroupLayout(rotationChart);
        rotationChart.setLayout(rotationChartLayout);
        rotationChartLayout.setHorizontalGroup(
            rotationChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        rotationChartLayout.setVerticalGroup(
            rotationChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(rotationChart, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RotationChartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RotationChartFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rotationChart;
    // End of variables declaration//GEN-END:variables
}
